name: GitHub Actions Expressions

on:
  push:
  workflow_dispatch:

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
    - id: guidgen
      name: Generate GUID
      shell: pwsh
      run: |
        Write-Output ('::set-output name=Decider::asdf{0}' -f (New-Guid).Guid)
    - name: Print GUID from previous step
      shell: pwsh
      run: |
        Write-Host -Object '${{ steps.outputs.guidgen.Decider }}'
