name: GitHub Actions Expressions

on:
  push:
  workflow_dispatch:

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
    - id: guidgen
      name: Generate GUID
      shell: pwsh
      run: |
        Write-Host -Object ('::set-output name=Decider::{0}' -f (New-Guid).Guid)
    - name: Print GUID from previous step
      shell: pwsh
      run: |
        Write-Host -Object '${{ steps.guidgen.outputs.Decider }}'
    - shell: pwsh
      name: Conditional Print
      if: ${{ startsWith(steps.guidgen.outputs.Decider, 'c') || startsWith(steps.guidgen.outputs.Decider, 'd') || startsWith(steps.guidgen.outputs.Decider, 'e') || startsWith(steps.guidgen.outputs.Decider, 'f') }}
      run: |
        Write-Host -Object '${{ steps.guidgen.outputs.Decider }}'
